### ISSUE TITLE
beta parsing doesn't support multi-electrode (matrix) input data

### ISSUE THREAD

**Issue by Tal-Golan** [edden-gerber/rERP-functions#4]
`b = X\input_data` can solve for multi-column `input_data` (each column representing an electrode), but the following lines assume `input_data` is a vector and will produce spurious results if not.

`glm_estimates = nan(max(window_length),num_event_types + num_extra_predictors + 1);
% Parse beta vector into segments
for ii = 1:num_event_types
    glm_estimates(1:window_length(ii),ii) = b(sum(window_length(1:ii-1))+1:sum(window_length(1:ii)));
end
% Parse beta values for additional predictors
for ii=1:num_extra_predictors
   glm_estimates(1,num_event_types+ii) = b(num_event_types*(window_length(1))+ii);
end`

In my opinion `glm_estimates` should be a struct. Each condition will be represented by a different element, with it's x-axis (time vector), name, and beta vector/matrix. Alternative, in order to support multi-electrode data, `glm_estimates` has to be a 3d matrix.

**Comment by edden-gerber** [comment]
If those are the only lines incompatible with multi-column input, then there's no reason to change them (seems pretty straightforward). 
I would prefer a 3d output over a struct, mostly because a struct is more cumbersome to deal with as output (loops etc.). Also - if you can match a condition to a name and time vector and specify them as additional input when you call the function, you can just as well do it one line later when you read the result - seems unnecessary to me. 
If you modify the code to allows 3D input/output I will merge it and update Common Resources - it should be backward-compatible anyway.
